### ISSUE TITLE
Board visibility, posting and file types are not enabled by default 

### ISSUE THREAD

**Issue by LeBron-James-Official** [WillBoard/WillBoard#3]
Hi there!
It seems there's a mistake and in board confing (or 'Update' as it's called) these things are not enabled by default. Adding them would save a lot of time and make the process of creating new boards much easier. Also I think there should be some selection of default filetypes like ["image/jpeg","image/png","image/gif","video/webm","audio/webm"] so the user wouldn't have to enter them manually. Hope you'll fix this!

**Comment by AnonimasDeveloper** [comment]
Disabled by default board visibility is correct. Board should not be visible until you intentionally turn it on. The same goes for the file types. It would be nice to add tooltips with examples to the fields in future.

**Comment by AnonimasDeveloper** [comment]
Disabled by default board visibility is correct. Board should not be visible until you intentionally turn it on. The same goes for the file types. It would be nice to add tooltips with examples to the fields in future.
