### ISSUE TITLE
Needs CoC

### ISSUE THREAD

**Issue by numberisnan** [WillBoard/WillBoard#5]
Hi, for the safety of the community, I think it would be beneficial to have a CoC. You could draw inspiration from Freedesktop's CCCoC (https://www.freedesktop.org/wiki/CodeOfConduct). With this change I think many marginalized people would feel more comfortable contributing to the project and engaging with the community.

**Comment by anonymousmaggot** [comment]
Lock it. Lock it now. This is the friendliest message I'm going to send, while I look for ways to get @WillBoard banned from 4chan for gross social misconduct. I imagine that "Stealing >>99999999" might be enough to get them tagged as a bot, who knows how many communities across however many generals that person just bothered across all of /g/.

**Comment by AnonimasDeveloper** [comment]
There is no need for any code of conduct at this stage.

**Comment by numberisnan** [comment]
I disagree, I think it is crucial to set expectations of inclusivity and professional conduct early on in the project's development. Doing so will also make it more likely for people to join knowing that this project takes these things seriously.
